# This file was generated by Limelight.
# It is automtically added to frozen gems.  When Limelight loads a production, it will load all 'limelight_init.rb'
# files, like this one, in each of the frozen gems.

Limelight::Gems.install('limelight_rdoc-0.1.8', ["lib"])
