class_name :text => 'Image'
method_name :text => 'image'
method_name :text => 'image='
method_name :text => 'rotation'
method_name :text => 'rotation='
method_name :text => 'scaled='
method_name :text => 'scaled?'
