class_name :text => 'OpenCommand'
method_name :text => 'description'
method_name :text => 'new'
method_name :text => 'do_requires'
method_name :text => 'parameter_description'
method_name :text => 'parse_remainder'
method_name :text => 'process'
