class_name :text => 'Templater'
method_name :text => 'clarify'
method_name :text => 'new'
method_name :text => 'source_dir'
method_name :text => 'directory'
method_name :text => 'establish_directory'
method_name :text => 'file'
method_name :text => 'replace_tokens'
