class_name :text => 'ClassName: Limelight::Commands::HelpCommand'
class_description :text => 'Prints limelight command help'
public_methods_header :text => 'Public Methods'
method_name :text => 'sort_commands'
method_description :text => ''
