class_name :text => 'ClassName: Limelight::Builtin::Players::Image'
class_description :text => ''
public_methods_header :text => 'Public Methods'
method_name :text => 'image'
method_description :text => ''
method_name :text => 'image='
method_description :text => ''
method_name :text => 'rotation'
method_description :text => ''
method_name :text => 'rotation='
method_description :text => ''
method_name :text => 'scaled='
method_description :text => ''
method_name :text => 'scaled?'
method_description :text => ''
