class_name :text => 'Playbill'
method_name :text => 'from_element'
method_name :text => 'new'
method_name :text => 'coerce_value'
method_name :text => 'llp'
method_name :text => 'populate_from_element'
method_name :text => 'pull'
method_name :text => 'thumbnail'
