class_name :text => 'RadioButton'
method_name :text => 'checked'
method_name :text => 'checked='
method_name :text => 'checked?'
method_name :text => 'group='
method_name :text => 'selected'
method_name :text => 'selected='
method_name :text => 'selected?'
