prop_to_extend :players => "text_box", :right_padding => "15"
key_presses :id => "key_presses", :text => "0"
generic_prop :text => " key presses        "
key_releases :id => "key_releases", :text => "0"
generic_prop :text => " key releases"